spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/product_search?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  autoconfigure:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: NOT_NULL
  mapper-locations: classpath*:/mapper/**/*.xml